export const BOOTH_CATALOG = [
  { key: 'standard-booth', label: 'Standard Booth', type: 'booth_standard', w: 3, h: 3, category: 'booth' },
  { key: 'large-booth', label: 'Large Booth', type: 'booth_large', w: 6, h: 3, category: 'booth' },
  { key: 'corner-booth', label: 'Corner Booth', type: 'booth_corner', w: 4, h: 4, category: 'booth' },
  { key: 'island-booth', label: 'Island Booth', type: 'booth_island', w: 6, h: 6, category: 'booth' },
  { key: 'entrance', label: 'Entrance', type: 'entrance', w: 3, h: 0.5, category: 'facility' },
  { key: 'exit', label: 'Exit', type: 'exit', w: 3, h: 0.5, category: 'facility' },
  { key: 'restroom', label: 'Restroom', type: 'restroom', w: 3, h: 2, category: 'facility' },
  { key: 'food-area', label: 'Food Court', type: 'food', w: 5, h: 4, category: 'facility' },
  { key: 'info-desk', label: 'Info Desk', type: 'info', w: 2, h: 2, category: 'facility' },
  { key: 'door', label: 'Door', type: 'door', w: 2, h: 0.4, category: 'structure', orientation: 'horizontal' },
  { key: 'window', label: 'Window', type: 'window', w: 3, h: 0.25, category: 'structure', orientation: 'horizontal' },
  { key: 'blind-path', label: 'Tactile Path', type: 'blind_path', w: 1, h: 6, category: 'structure', orientation: 'horizontal' }
];

export const PRESET_LAYOUTS = [
  {
    id: 'standard',
    name: 'Standard Layout',
    description: 'Grid layout with main entrance and facilities',
    hallWidth: 40,
    hallHeight: 30,
    booths: [
      { type: 'booth_standard', x: 3, y: 3, label: 'Booth 1' },
      { type: 'booth_standard', x: 3, y: 7, label: 'Booth 2' },
      { type: 'booth_standard', x: 3, y: 11, label: 'Booth 3' },
      { type: 'booth_standard', x: 3, y: 15, label: 'Booth 4' },
      { type: 'booth_standard', x: 3, y: 19, label: 'Booth 5' },
      { type: 'booth_large', x: 8, y: 3, label: 'Booth 6' },
      { type: 'booth_large', x: 8, y: 7, label: 'Booth 7' },
      { type: 'booth_standard', x: 8, y: 11, label: 'Booth 8' },
      { type: 'booth_standard', x: 8, y: 15, label: 'Booth 9' },
      { type: 'booth_large', x: 8, y: 19, label: 'Booth 10' },
      { type: 'booth_large', x: 16, y: 3, label: 'Booth 11' },
      { type: 'booth_large', x: 16, y: 7, label: 'Booth 12' },
      { type: 'booth_standard', x: 16, y: 11, label: 'Booth 13' },
      { type: 'booth_standard', x: 16, y: 15, label: 'Booth 14' },
      { type: 'booth_large', x: 16, y: 19, label: 'Booth 15' },
      { type: 'booth_standard', x: 24, y: 3, label: 'Booth 16' },
      { type: 'booth_standard', x: 24, y: 7, label: 'Booth 17' },
      { type: 'booth_standard', x: 24, y: 11, label: 'Booth 18' },
      { type: 'booth_standard', x: 24, y: 15, label: 'Booth 19' },
      { type: 'booth_standard', x: 24, y: 19, label: 'Booth 20' },
      { type: 'booth_island', x: 30, y: 3, label: 'Island 1' },
      { type: 'booth_island', x: 30, y: 12, label: 'Island 2' }
    ],
    facilities: [
      { type: 'entrance', x: 18, y: 0.2, label: 'Main Entrance' },
      { type: 'exit', x: 5, y: 29.3, label: 'Emergency Exit' },
      { type: 'exit', x: 30, y: 29.3, label: 'Emergency Exit' },
      { type: 'restroom', x: 1, y: 25, label: 'Restrooms' },
      { type: 'food', x: 30, y: 21, label: 'Food Court' },
      { type: 'info', x: 18, y: 1.5, label: 'Info Desk' },
      { type: 'window', x: 4, y: 0.2, label: 'North Window' },
      { type: 'window', x: 32, y: 0.2, label: 'North Window' },
      { type: 'door', x: 18, y: 29.6, label: 'Service Door' },
      { type: 'blind_path', x: 18, y: 4, label: 'Tactile Path', scaleY: 4 }
    ]
  },
  {
    id: 'compact',
    name: 'Compact Layout',
    description: 'Smaller space with mixed booth sizes',
    hallWidth: 30,
    hallHeight: 24,
    booths: [
      { type: 'booth_corner', x: 3, y: 3, label: 'Corner 1' },
      { type: 'booth_standard', x: 8, y: 3, label: 'Booth 1' },
      { type: 'booth_standard', x: 12, y: 3, label: 'Booth 2' },
      { type: 'booth_corner', x: 16, y: 3, label: 'Corner 2' },
      { type: 'booth_large', x: 3, y: 8, label: 'Booth 3' },
      { type: 'booth_large', x: 10, y: 8, label: 'Booth 4' },
      { type: 'booth_large', x: 17, y: 8, label: 'Booth 5' },
      { type: 'booth_standard', x: 3, y: 12, label: 'Booth 6' },
      { type: 'booth_island', x: 7, y: 12, label: 'Island' },
      { type: 'booth_standard', x: 14, y: 12, label: 'Booth 7' },
      { type: 'booth_standard', x: 18, y: 12, label: 'Booth 8' },
      { type: 'booth_standard', x: 3, y: 16, label: 'Booth 9' },
      { type: 'booth_standard', x: 7, y: 16, label: 'Booth 10' },
      { type: 'booth_large', x: 11, y: 16, label: 'Booth 11' },
      { type: 'booth_standard', x: 18, y: 16, label: 'Booth 12' }
    ],
    facilities: [
      { type: 'entrance', x: 13, y: 0.2, label: 'Entrance' },
      { type: 'exit', x: 3, y: 23.3, label: 'Exit' },
      { type: 'restroom', x: 24, y: 3, label: 'Restrooms' },
      { type: 'food', x: 24, y: 8, label: 'Food Area' },
      { type: 'info', x: 13, y: 1.5, label: 'Info' },
      { type: 'window', x: 6, y: 0.2, label: 'North Window' },
      { type: 'window', x: 20, y: 0.2, label: 'North Window' },
      { type: 'door', x: 13, y: 23.5, label: 'Rear Door' },
      { type: 'blind_path', x: 13, y: 4, label: 'Tactile Path', scaleY: 3 }
    ]
  },
  {
    id: 'premium',
    name: 'Premium Layout',
    description: 'Spacious layout with premium island booths',
    hallWidth: 50,
    hallHeight: 35,
    booths: [
      { type: 'booth_island', x: 15, y: 8, label: 'Premium Island 1' },
      { type: 'booth_island', x: 25, y: 8, label: 'Premium Island 2' },
      { type: 'booth_island', x: 15, y: 18, label: 'Premium Island 3' },
      { type: 'booth_island', x: 25, y: 18, label: 'Premium Island 4' },
      { type: 'booth_large', x: 3, y: 3, label: 'Booth 1' },
      { type: 'booth_large', x: 3, y: 7, label: 'Booth 2' },
      { type: 'booth_large', x: 3, y: 11, label: 'Booth 3' },
      { type: 'booth_large', x: 3, y: 15, label: 'Booth 4' },
      { type: 'booth_large', x: 3, y: 19, label: 'Booth 5' },
      { type: 'booth_large', x: 3, y: 23, label: 'Booth 6' },
      { type: 'booth_large', x: 40, y: 3, label: 'Booth 7' },
      { type: 'booth_large', x: 40, y: 7, label: 'Booth 8' },
      { type: 'booth_large', x: 40, y: 11, label: 'Booth 9' },
      { type: 'booth_large', x: 40, y: 15, label: 'Booth 10' },
      { type: 'booth_large', x: 40, y: 19, label: 'Booth 11' },
      { type: 'booth_large', x: 40, y: 23, label: 'Booth 12' },
      { type: 'booth_corner', x: 10, y: 3, label: 'Corner 1' },
      { type: 'booth_corner', x: 35, y: 3, label: 'Corner 2' },
      { type: 'booth_corner', x: 10, y: 28, label: 'Corner 3' },
      { type: 'booth_corner', x: 35, y: 28, label: 'Corner 4' }
    ],
    facilities: [
      { type: 'entrance', x: 23, y: 0.2, label: 'Main Entrance' },
      { type: 'exit', x: 10, y: 34.3, label: 'Exit Left' },
      { type: 'exit', x: 35, y: 34.3, label: 'Exit Right' },
      { type: 'restroom', x: 44, y: 28, label: 'Restrooms' },
      { type: 'food', x: 10, y: 15, label: 'Food Court' },
      { type: 'info', x: 23, y: 2, label: 'Info Desk' },
      { type: 'window', x: 6, y: 0.2, label: 'North Window' },
      { type: 'window', x: 40, y: 0.2, label: 'North Window' },
      { type: 'door', x: 23, y: 34.6, label: 'Loading Door' },
      { type: 'blind_path', x: 23, y: 6, label: 'Tactile Path', scaleY: 4 }
    ]
  }
];
