# Generated by Django 5.2.7 on 2025-10-13 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_conferenceevent_conferenceelement_conferenceguest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#3B82F6", max_length=20)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="api.conferenceevent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conferenceguest",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guests",
                to="api.conferencegroup",
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceguest",
            index=models.Index(fields=["group"], name="api_confere_group_i_88a4c0_idx"),
        ),
        migrations.AddIndex(
            model_name="conferencegroup",
            index=models.Index(fields=["event"], name="api_confere_event_i_d5dc77_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="conferencegroup",
            unique_together={("event", "name")},
        ),
    ]
