# Generated by Django 5.2.6 on 2025-10-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conferenceevent_conferenceelement_conferencegroup_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='designshare',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='designshare',
            name='design',
        ),
        migrations.RemoveField(
            model_name='designshare',
            name='user',
        ),
        migrations.DeleteModel(
            name='DesignLink',
        ),
        migrations.DeleteModel(
            name='DesignShare',
        ),
    ]
