# Generated by Django 5.2.6 on 2025-10-21 09:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_designshare_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('speaker', models.CharField(blank=True, max_length=255)),
                ('speaker_title', models.CharField(blank=True, max_length=255)),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('keynote', 'Keynote'), ('workshop', 'Workshop'), ('panel', 'Panel Discussion'), ('demo', 'Demonstration'), ('break', 'Break/Networking'), ('ceremony', 'Ceremony'), ('presentation', 'Presentation'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('conference_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.conferenceevent')),
                ('tradeshow_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.tradeshowevent')),
            ],
            options={
                'ordering': ['session_date', 'start_time'],
                'indexes': [models.Index(fields=['conference_event'], name='api_eventse_confere_52a3db_idx'), models.Index(fields=['tradeshow_event'], name='api_eventse_tradesh_43d00b_idx'), models.Index(fields=['session_date', 'start_time'], name='api_eventse_session_be94a5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('conference_event__isnull', False), ('tradeshow_event__isnull', True)), models.Q(('conference_event__isnull', True), ('tradeshow_event__isnull', False)), _connector='OR'), name='session_belongs_to_one_event_type')],
            },
        ),
    ]
