# Generated by Django 5.2.6 on 2025-10-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_eventsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceguest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
