# Generated by Django 5.2.6 on 2025-10-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_make_email_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeshowbooth',
            name='booth_type',
            field=models.CharField(choices=[('booth_standard', 'Standard Booth'), ('booth_large', 'Large Booth'), ('booth_premium', 'Premium Booth'), ('booth_island', 'Island Booth'), ('aisle', 'Aisle'), ('tactile_paving', 'Tactile Paving'), ('waiting_area', 'Waiting Area'), ('restroom', 'Restroom'), ('info_desk', 'Info Desk'), ('door1', 'Door (Style 1)'), ('door2', 'Door (Style 2)'), ('power_outlet', 'Power Outlet')], max_length=50),
        ),
    ]
