# Generated by Django 5.2.6 on 2025-10-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_tradeshow_booth_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeshowroute',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=20),
        ),
        migrations.AddField(
            model_name='tradeshowroute',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
