# Generated by Django 5.2.6 on 2025-10-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_route_color_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceelement',
            name='element_type',
            field=models.CharField(choices=[('table_round', 'Round Table'), ('table_rectangle', 'Rectangle Table'), ('chair', 'Chair'), ('podium', 'Podium'), ('stage', 'Stage'), ('door', 'Door'), ('outlet', 'Outlet'), ('window', 'Window'), ('tactile_paving', 'Tactile Paving'), ('custom', 'Custom Element')], max_length=50),
        ),
    ]
