# Generated by Django 5.2.6 on 2025-10-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_decoration_element_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceevent',
            name='room_height',
            field=models.FloatField(default=16.0),
        ),
        migrations.AlterField(
            model_name='conferenceevent',
            name='room_width',
            field=models.FloatField(default=24.0),
        ),
    ]
