# Generated by Django 5.2.6 on 2025-10-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_conferenceevent_room_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeshowevent',
            name='hall_height',
            field=models.FloatField(default=30.0),
        ),
        migrations.AlterField(
            model_name='tradeshowevent',
            name='hall_width',
            field=models.FloatField(default=40.0),
        ),
    ]
